### ISSUE TITLE
old egw image

### ISSUE THREAD

**Issue by davmoz** [srcfl/egw-diy#1]
We need a newer picture of the egw (one w/o antenna).

**Comment by VIKOLO** [comment]
![image](https://github.com/srcfl/egw-diy/assets/126172118/8e26ff89-8250-4318-a831-09f771127756)

**Comment by VIKOLO** [comment]
![image](https://github.com/srcfl/egw-diy/assets/126172118/ab25ea99-da31-4ebb-9c2b-af8148f824a7)

**Comment by VIKOLO** [comment]
![image](https://github.com/srcfl/egw-diy/assets/126172118/f000a989-4980-4b98-9d99-545cdaaf60bb)
